[server]
headless = true
enableCORS = false
maxUploadSize = 1024
websocketPingInterval = 20

[theme]
primaryColor="#FF6B6B"
backgroundColor="#F8F0E5"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"